name: CI

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Dotnet Publish
      run: dotnet publish -c Release -o deploy
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@v0.7.1
      with:
        local: /home/runner/work/WebAppCI/WebAppCI/deploy/
        remote: /var/www/webappci
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
